version: '3'

services:
  mysqlsrv:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2022!"
    ports:
      - "3306:3306"
    volumes:
      - ./MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8090:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
