spring:
    datasource:
        url: jdbc:mysql://localhost:3306/med_api
        username: root
        password: MySql2022!
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
    error:
        # remove stack trace para retornos de erro da api
        include-stacktrace: never