### Login
POST {{base-url}}/login
content-type: application/json

{
    "login" : "elton@email.com",
    "senha": "elton"
}

######
@token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbHRvbkBlbWFpbC5jb20iLCJpc3MiOiJBUEkgTWVkaWNhIiwiaWQiOjIsImV4cCI6MTY3MjI2OTM4MX0.SA7ziVh8q82-3k7-_Gj1mS-lny7c10Ky-bEGVBbqQ1w

### Cadastrar médico
POST {{base-url}}/medicos
content-type: application/json
Authorization: {{token}}

{
    "nome" : "Elton 02",
    "email": "elton02@email.com",
    "crm": "123457",
    "telefone": "1234",
    "especialidade" : "ORTOPEDIA",
    "endereco": {
        "logradouro": "rua da clinica",
        "bairro": "bairro da clinica",
        "cep": "20010731",
        "cidade": "uma cidade",
        "estado": "mg",
        "numero": "1",
        "complemento": "bloco 01"
    }
}

### Listar médicos
GET {{base-url}}/medicos
content-type: application/json
Authorization: {{token}}

### Listar médicos usando dados de paginação
GET {{base-url}}/medicos?page=0&size=1&sort=nome,desc
Authorization: {{token}}

### Inativar médico
DELETE {{base-url}}/medicos/2
content-type: application/json
Authorization: {{token}}

